services:
  s1admin:
    image: dpage/pgadmin4
    container_name: CyberHub-Admin
    restart: always
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    ports:
      - "127.0.0.1:${ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASS}
    networks:
      - cyberhub-network