services: 
  CyberHub-S1_app:
    image: prawee/strapi:latest
    container_name: CyberHub-App
    ports:
      - "${APP_PORT}:1337"
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
    networks:
      - cyberhub-network