# docker-compose.yaml
include:
  - db.yaml
  - admin.yaml
  - app.yaml

services:
  cyberhub-web: # ชื่อ Web Server ตามโจทย์อาจารย์
    extends:
      file: app.yaml
      service: CyberHub-S1_app
    networks:
      - cyberhub-network

networks:
  cyberhub-network:
    driver: bridge