include:
  - app.yaml

services:
  caddy:
    image: caddy:latest
    container_name: 68_s1_Cyberhub-s1_Caddy
    restart: always
    security_opt:
      - no-new-privileges:true
    container_name: CyberHub-Caddy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    ports:
      - "8888:80"
      #- "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - cyberhub-network
